bomb breaks blocks
vinport16/chunkball pull request #42
Opened 2023-01-19 22:02 UTC by vinport16

check this out. u can break blocks with the bomb loadout

lmk how you feel about this

2023-01-19 23:14 UTC, mes258 commented
This is awesome! If a player shoots a bomb right before the map refresh, the projectile lands and destroys the new map after the refresh. When we refresh the map, lets also delete all projectiles. Also, the bomb is really powerful now. We should either lower the available shots, or significantly increase the reload time.

2023-01-19 23:25 UTC, mes258 approved these changes

2023-01-19 23:48 UTC, mes258 requested changes
If a player shoots a bomb at an unloaded chunk, there is an error when the chunk updates: 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/20585567/213587075-dd1bc0d5-c9d8-426b-bd48-7baad69bde2d.png">

2023-01-20 02:10 UTC, vinport16 commented
> If a player shoots a bomb at an unloaded chunk, there is an error when the chunk updates: <img alt="image" width="566" src="https://user-images.githubusercontent.com/20585567/213587075-dd1bc0d5-c9d8-426b-bd48-7baad69bde2d.png">

good catch. I left in a couple lines I meant to remove. fixed now.

2023-01-20 18:21 UTC, mes258 approved these changes

2023-01-20 18:22 UTC, merged